### **Why Numpy**

|          | Python Lists     | Numpy Arrays |
|:--------------:|:-----------:|:------------:|
|**Data Types**      |  Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations. |  NumPy arrays store elements of the same data type, making them more compact and memory-efficient than lists.       |
| **Memory Fragmentation**| Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.  | NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.       |These operations are implemented in C, resulting in faster performance than equivalent operations on lists.
| **Functionality** |  Lists can store any data type, but lack specialized NumPy functions for numerical operations.| NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are implemented in C, resulting in faster performance than equivalent operations on lists.|


In [708]:
import numpy as np

## **Array Creation**
- **np.array(Array[values], dtype=float)**

In [709]:
arr_float = np.array([1, 2.2, 3.3], dtype=float)  # float array
print(arr_float)

[1.  2.2 3.3]


In [710]:
# Get Dimension
arr = np.array([[1, 2, 3, 4],[5,6,7,8]])
arr.ndim

2

### **1D Array**

In [711]:
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

### **2D Array**

In [712]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

### **3D Array**

In [713]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [714]:
a = np.array([[1, 2], [3, 4]])

In [715]:
# Get a specific row 
a[0, :]

array([1, 2])

In [716]:
# Get a specific column
a[:, 1]

array([2, 4])

### **Zeros and Ones Matrix**

In [717]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [718]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **Identify Matrix**

In [719]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [720]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### **Diagonal Matrix**

In [721]:
np.diag((-3, -4 , 4 , 6))

array([[-3,  0,  0,  0],
       [ 0, -4,  0,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  6]])

### **Matrix of the Particular Number**

In [722]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

### **Repeat an array**

In [723]:
arr = np.array([[1,2,3]])
np.repeat(arr,3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### **Numpy.Arange**
- **arange([start,] stop[, step,][, dtype])**

In [724]:
np.arange(1,10,2) ## start -> 1 , end -> 10 ,step-> 2

array([1, 3, 5, 7, 9])

### **Slicing and Striding**

In [725]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])  # From index 1 to index 5
print(arr[4:])   # From index 4 to the end of the array
print(arr[:4])   # From the beginning to index 4

[2 3 4 5]
[5 6 7]
[1 2 3 4]


### **NumPy Copy**
- **By default, NumPy passes arrays by reference. You can make a copy using arr.copy()**


In [726]:
arr = np.array([1, 2, 3, 4])  # 1D array
arr_copy = arr.copy()  # Make a copy of the array
arr_copy[0] = 99

print("Original Array:", arr)
print("Copy:", arr_copy)


Original Array: [1 2 3 4]
Copy: [99  2  3  4]


### **NumPy View**
- **By default, NumPy passes arrays by reference. You can make a copy using arr.copy(), otherwise, you'll be working with a view.**


In [727]:
arr = np.array([1, 2, 3, 4])  # 1D array
arr_view = arr.view()  # Create a view of the array
arr_view[0] = 88

print("Original Array:", arr)
print("View:", arr_view)

Original Array: [88  2  3  4]
View: [88  2  3  4]


### **Numpy.Random**

In [728]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.04240814, 0.60666406],
       [0.54207938, 0.99573272],
       [0.86355285, 0.94581578],
       [0.03083658, 0.96089897]])

In [729]:
# Random Integer values
np.random.randint(1,10,size=(3,3))

array([[4, 3, 2],
       [4, 3, 7],
       [1, 7, 3]])

### **Statistics**

In [730]:
a = np.arange(1, 17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [731]:
# Maximum of Array
np.max(a)

np.int64(16)

In [732]:
# Maximum of Each Cols of  the Array
np.max(a,axis=0) 

array([13, 14, 15, 16])

In [733]:
# Maximum of Each Row of  the Array
np.max(a,axis=1) 

array([ 4,  8, 12, 16])

In [734]:
# Minimum of Array
np.min(a)

np.int64(1)

In [735]:
# Minimum of Each Cols of  the Array
np.min(a,axis=0)

array([1, 2, 3, 4])

In [736]:
# Minimum of Each Row of  the Array
np.min(a,axis=1)

array([ 1,  5,  9, 13])

In [737]:
# Determinant -> Compute the determinant of an array.
stat = np.array([[6, 9], [8, 8]])
np.linalg.det(stat)

np.float64(-23.999999999999993)

In [738]:
# Trace  -> Return the sum along diagonals of the array.
np.trace(stat)

np.int64(14)

In [739]:
np.trace(stat, offset=1, axis1=1, axis2=0, dtype=None, out=None)

np.int64(8)

In [740]:
# Eignenvalues -> Compute the eigenvalues and right eigenvectors of a square array.
np.linalg.eig(stat)

EigResult(eigenvalues=array([-1.54400375, 15.54400375]), eigenvectors=array([[-0.76637529, -0.68606807],
       [ 0.64239312, -0.72753736]]))

In [741]:
eigenvalues, eigenvectors = np.linalg.eig(stat)
print("eigenvalues:",eigenvalues)
print("eigenvectors:",eigenvectors)

eigenvalues: [-1.54400375 15.54400375]
eigenvectors: [[-0.76637529 -0.68606807]
 [ 0.64239312 -0.72753736]]


In [742]:
np.linalg.eigvals(stat)

array([-1.54400375, 15.54400375])

In [743]:
# Matrix Norm ->Computes the matrix norm of a matrix (or a stack of matrices)
np.linalg.matrix_norm(stat)

np.float64(15.652475842498529)

In [744]:
# Inverse ->Compute the inverse of a matrix.
np.linalg.inv(stat)

array([[-0.33333333,  0.375     ],
       [ 0.33333333, -0.25      ]])

In [745]:
# Transposes ->Transposes a matrix (or a stack of matrices)
np.linalg.matrix_transpose(stat)

array([[6, 8],
       [9, 8]])