|          | Python Lists     | Numpy Arrays |
|:--------------:|:-----------:|:------------:|
|**Data Types**      |  Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations. |  NumPy arrays store elements of the same data type, making them more compact and memory-efficient than lists.       |
| **Memory Fragmentation**| Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.  | NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.       |These operations are implemented in C, resulting in faster performance than equivalent operations on lists.
| **Functionality** |  Lists can store any data type, but lack specialized NumPy functions for numerical operations.| NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are implemented in C, resulting in faster performance than equivalent operations on lists.|


In [17]:
import numpy as np

## **Array Creation**
- **np.array(Array[values], dtype=float)**

In [18]:
arr_float = np.array([1, 2.2, 3.3], dtype=float)  # float array
print(arr_float)

[1.  2.2 3.3]


### **1D Array**

In [19]:
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

### **2D Array**

In [20]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

### **3D Array**

In [21]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### **Zeros and Ones Matrix**

In [22]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **Identify Matrix**

In [24]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### **Diagonal Matrix**

In [25]:
np.diag((-3, -4 , 4 , 6))

array([[-3,  0,  0,  0],
       [ 0, -4,  0,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  6]])

### **Numpy.Arange**
- **arange([start,] stop[, step,][, dtype])**

In [26]:
np.arange(1,10,2) ## start -> 1 , end -> 10 ,step-> 2

array([1, 3, 5, 7, 9])

### **Slicing and Striding**

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])  # From index 1 to index 5
print(arr[4:])   # From index 4 to the end of the array
print(arr[:4])   # From the beginning to index 4

[2 3 4 5]
[5 6 7]
[1 2 3 4]


### **NumPy Copy**
- **By default, NumPy passes arrays by reference. You can make a copy using arr.copy()**


In [28]:
arr = np.array([1, 2, 3, 4])  # 1D array
arr_copy = arr.copy()  # Make a copy of the array
arr_copy[0] = 99

print("Original Array:", arr)
print("Copy:", arr_copy)


Original Array: [1 2 3 4]
Copy: [99  2  3  4]


### **NumPy View**
- **By default, NumPy passes arrays by reference. You can make a copy using arr.copy(), otherwise, you'll be working with a view.**


In [29]:
arr = np.array([1, 2, 3, 4])  # 1D array
arr_view = arr.view()  # Create a view of the array
arr_view[0] = 88

print("Original Array:", arr)
print("View:", arr_view)

Original Array: [88  2  3  4]
View: [88  2  3  4]
