In [2]:
import numpy as np

## **Array Creation**

### **1D Array**

In [14]:
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

### **2D Array**

In [15]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

### **3D Array**

In [16]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### **Zeros and Ones Matrix**

In [18]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **Identify Matrix**

In [24]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### **Diagonal Matrix**

In [27]:
np.diag((-3, -4 , 4 , 6))

array([[-3,  0,  0,  0],
       [ 0, -4,  0,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  6]])

### **Numpy.Arange**
- **arange([start,] stop[, step,][, dtype])**

In [31]:
np.arange(1,10,2) ## start -> 1 , end -> 10 ,step-> 2

array([1, 3, 5, 7, 9])

### **Slicing and Striding**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])  # From index 1 to index 5
print(arr[4:])   # From index 4 to the end of the array
print(arr[:4])   # From the beginning to index 4

[2 3 4 5]
